// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Backup_Directories(arg1:Array<string>):Promise<Array<boolean>>;

export function Backup_Packages():Promise<boolean>;

export function Get_App_List():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function Pick_Directory():Promise<string>;
