// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Backup_Directories(arg1) {
  return window['go']['main']['App']['Backup_Directories'](arg1);
}

export function Backup_Packages() {
  return window['go']['main']['App']['Backup_Packages']();
}

export function Get_App_List() {
  return window['go']['main']['App']['Get_App_List']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Pick_Directory() {
  return window['go']['main']['App']['Pick_Directory']();
}
